2808 - es6 conversion
adaptlearning/adapt-extension pull request #1
Opened 2022-05-09 10:52 UTC by eleanor-heath

https://github.com/adaptlearning/adapt_framework/issues/2808

2022-05-09 11:00 UTC, cahirodoherty-learningpool commented on js/adapt-extension.js
> +import Adapt from 'coreJS/adapt';
Minor: 'core/js/adapt' ?

2022-05-09 11:02 UTC, cahirodoherty-learningpool commented on js/adapt-extensionView.js
> +import Adapt from 'coreJS/adapt';
Minor: 'core/js/adapt'

2022-05-09 11:04 UTC, cahirodoherty-learningpool commented on js/adapt-extensionView.js
> +import Adapt from 'coreJS/adapt';
```suggestion
import Adapt from 'core/js/adapt';
```

2022-05-09 11:04 UTC, cahirodoherty-learningpool commented on js/adapt-extension.js
> +import Adapt from 'coreJS/adapt';
```suggestion
import Adapt from 'core/js/adapt';
```

2022-05-09 12:31 UTC, cahirodoherty-learningpool approved these changes
👀

2022-05-09 12:31 UTC, ethan-lp approved these changes

2022-05-10 09:41 UTC, oliverfoster requested changes

2022-05-10 09:41 UTC, oliverfoster commented on js/adapt-extension.js
> +    Adapt.listenTo('app:dataReady', function() {
```js
  this.listenTo(Adapt, 'app:dataReady', this.onDataReady);
}

onDataReady() {
  console.log('Plugin has loaded and data is ready');
}
```

2022-05-10 09:41 UTC, oliverfoster commented on js/adapt-extension.js
> +import ExtensionView from 'extensions/adapt-extension/js/adapt-extensionView';
call the view class file: `ExtensionView.js`

2022-05-10 10:11 UTC, oliverfoster commented on js/adapt-extension.js
> +import ExtensionView from 'extensions/adapt-extension/js/ExtensionView.js';
```suggestion
import ExtensionView from 'extensions/adapt-extension/js/ExtensionView';
```

don't need the `.js` here.

2022-05-10 10:22 UTC, oliverfoster commented on js/adapt-extension.js
> +    Adapt.listenTo('app:dataReady', function() {
Missed this bit:

```js
  this.listenTo(Adapt, 'app:dataReady', this.onDataReady);
```

2022-05-10 10:29 UTC, oliverfoster approved these changes

2022-05-23 11:02 UTC, merged